---
### group_vars/DC1_FABRIC.yml

fabric_name: DC1_FABRIC

# Set Design Type to L2ls
#design:
#  type: l2ls

# Spine Switches
l2spine:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 172.16.1.0/24
    mlag_peer_ipv4_pool: 192.168.55.0/24
    mlag_peer_l3_ipv4_pool: 10.1.1.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    mlag_interfaces: [Ethernet55/1, Ethernet56/1]
  node_groups:
    - group: SPINES
      nodes:
        - name: spine1
          id: 1
          mgmt_ip: 192.168.0.111/24
        - name: spine2
          id: 2
          mgmt_ip: 192.168.0.112/24

# IDF - Leaf Switches

#campus_access_pod: BUILDING-A
#cv_tags_topology_type: "member-leaf"

l2leaf:
  defaults:
    platform: vEOS-lab
    mlag_peer_ipv4_pool: 192.168.55.0/24
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    - group: POD-4
      mlag: false
      nodes:
        - name: pod-4-1
          id: 5
          mgmt_ip: 192.168.0.20/24
          uplink_interfaces: [Ethernet49, Ethernet50]
          uplink_switches: [spine1, spine2]
          uplink_switch_interfaces: [Ethernet4, Ethernet4]


#### Override for vEOS/cEOS Lab Caveats ####
p2p_uplinks_mtu: 1500

# Underlay Routing Protocol
underlay_routing_protocol: ospf

#### WAN/Core Edge Links ####

