---
# deploy.yml

- name: Configuration deployment
  hosts: FABRIC # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 10.18.163.249
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc2Mjg3ODg3NzU5MzM0NDQzNDUsImRzbiI6ImF2ZCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NzY3Nzk5OTksImlhdCI6MTc3NjIxNzIwNCwib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiZWY5N2M0OWYxYzE4MjQwMTcwMTcwZjQ1MjYyM2M0OWViNGQ2YTA0N2NmYzZlMzJmMDljOWVhZjFjMjk5NzVkNy05R205bzdWMFhWenFlU1RPY25CNnZyV3E1N3AxRGJEUjZJR0o0b0N5In0.DBMiz6_a8xSisvshfDPfAfqqRdhMTkBKwN9UCo0XwdupL_SJC2pcAXIsZtHnVqFZdwBJktZGENx5IVpjY4gyU276O73vSsBWQYiox5nZeldTptwLmHf5QmHp7ZHXyn0_N4heEl7boWCozD2DLSohEEQ3cFcF-5I21sB-Y-96Z5TfnNQOSRFv9WE4cKWPi_r06fxteI714W7TnSrX-vSUNxmFnQPX6cWCzKoecm90vKCn6wPTNNIMmsQYONmHbm4FqpcgrPAObYi1Dee_uDoaJC3UB9Tdn8vS_tRud7RbFmcuPMrtBLxQO8TzF0cSK7ALkAe4vCARhmuOHYBuPq3_RT7wZVXA4lNQEvI11Q7kfwFJMzRWGPHl-68hNAhhTTR8UxWNzjSTyqbEJSmpA4PruKjNBHXHMs0J2bP0vPOJ3fnrYYoDoe2lLqEThRYyRZJu8394rkuuUtqVaNbrMRIN7EzS3_q_EG6j2aFwceWdWtrgdV_XeWxIh7RqhrpRxiLPIIJFgJ-Gk_Tbpb5TPBLjd6CQp8fcBVPsM-wFuMyotdKPvPlzrKxVQcShVBl2OXwQX7M4rYDMYbwb0NjzBxXkCoF2BafVEVRknu2AfHmCTn6fhMF_AcMia88xXrCeQIb_28DOGnrV2vdLo-ObJIDSGpLQS6ti5dEt2lP-nv-C9XA
        cv_verify_certs: false